### ISSUE TITLE
some issue  on website build stage 

### ISSUE THREAD

**Issue by isemennikov** [spyboy-productions/omnisci3nt#1]
[~] Website build with :

^CTraceback (most recent call last):
  File "/app/omnisci3nt/omnisci3nt.py", line 299, in <module>
    programming_languages, technologies, javascript_libraries, web_server = analyze_website(website_url)
                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/omnisci3nt/buildwith.py", line 21, in analyze_website
    technologies = builtwith.builtwith(url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/builtwith/__init__.py", line 65, in builtwith
    if contains(html, snippet):
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/builtwith/__init__.py", line 111, in contains
    return re.compile(regex.split('\\;')[0], flags=re.IGNORECASE).search(v)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Exception ignored in: <__main__.Tee object at 0xffffa3ee6ed0>
AttributeError: 'Tee' object has no attribute 'flush'

**Comment by thisisshubhamkumar** [comment]
Seems like a keyboard interruption. we have tested it works fine for us. I don’t see any specific error you need to provide more info. if you are using on Windows use terminal(WSL2) instead of cmd/PowerShell otherwise, we recommend using it on Mac/Linux.

**Comment by isemennikov** [comment]
Hey 
Yes of course I use Mac keyboard only. 

What additional information would you like to have?
